Do not allow unknown plugin configurations
greenplum-db/gpbackup-s3-plugin pull request #37
Opened 2021-05-18 00:31 UTC by kyeap-vmware

There have been cases where an option was misspelled resulting in
unexpected behavior. Previously, s3 plugin would ignore unknown yaml
options. Now s3 plugin will error out immediately if it finds any
unknown configurations.

2021-05-18 22:51 UTC, jimmyyih approved these changes
Not sure how I feel about the hardcoded `validOptions` variable being stored in the `ValidateConfig` function but overall good change (especially the error aggregation which will be useful).  Maybe in the future we could switch to Viper for config file management instead.

2021-05-19 21:58 UTC, shivzone commented
Now that we are trying to delegating the responsibilitiy to validate the plugin config files to the underlying plugins, I think now is the time to refactor and do away with using `map[string]` which i always hated in the first place.
Lets replace with something link
```
type PluginOptions struct {
        Region              string            `yaml:"region"`
        AccessKey           string            `yaml:"aws_access_key_id"`
        SecretKey           string            `yaml:"aws_secret_access_key"`
        Bucket              string            `yaml:"bucket"`
        Folder              string            `yaml:"folder"`
        BackupMultipartChunksize string       `yaml:"backup_multipart_chunksize"`
        BackupMaxConcurrentRequests string    `yaml:"backup_max_concurrent_requests"`
        RestoreMultipartChunksize string      `yaml:"restore_multipart_chunksize"`
        RestoreMaxConcurrentRequests string   `yaml:"restore_max_concurrent_requests"`
        Endpoint        string `yaml:"endpoint"`
        Encryption      string `yaml:"encryption"`
}

type PluginConfig struct {
        ExecutablePath      string                   `yaml:"executablepath"`
        ConfigPath          string                   `yaml:"-"`
        Options             PluginOptions            `yaml:"options"`
}
```
And simply use `yaml.UnmarshalStrict`

2021-05-19 21:59 UTC, shivzone requested changes
Now that we are trying to delegating the responsibilitiy to validate the plugin config files to the underlying plugins, I think now is the time to refactor and do away with using `map[string]` which i always hated in the first place.
Lets replace with something link
```
type PluginOptions struct {
        Region              string            `yaml:"region"`
        AccessKey           string            `yaml:"aws_access_key_id"`
        SecretKey           string            `yaml:"aws_secret_access_key"`
        Bucket              string            `yaml:"bucket"`
        Folder              string            `yaml:"folder"`
        BackupMultipartChunksize string       `yaml:"backup_multipart_chunksize"`
        BackupMaxConcurrentRequests string    `yaml:"backup_max_concurrent_requests"`
        RestoreMultipartChunksize string      `yaml:"restore_multipart_chunksize"`
        RestoreMaxConcurrentRequests string   `yaml:"restore_max_concurrent_requests"`
        Endpoint        string `yaml:"endpoint"`
        Encryption      string `yaml:"encryption"`
}

type PluginConfig struct {
        ExecutablePath      string                   `yaml:"executablepath"`
        ConfigPath          string                   `yaml:"-"`
        Options             PluginOptions            `yaml:"options"`
}
```
And simply use `yaml.UnmarshalStrict`

2021-05-27 21:48 UTC, jimmyyih approved these changes

2021-06-04 16:46 UTC, shivzone approved these changes
Looks good

2021-06-04 22:43 UTC, merged